# Setup
title:            SacArts4ALL
tagline:          'SacArts4ALL'
description:      ‘SacArts4ALL’
url:              'http://code4sac.github.io/sacarts4all.org'
baseurl:          '/sacarts4all'

author:
  name:           'SacArts4ALL'
  url:            https://twitter.com/

# Custom vars
version:          1.1 | May 2017

github:
  repo:           https://github.com/code4sac/sacarts4all
